name = "PredefinedDynamicalSystems"
uuid = "31e2f376-db9e-427a-b76e-a14f56347a14"
repo = "https://github.com/JuliaDynamics/PredefinedDynamicalSystems.jl.git"
version = "1"

[deps]
DynamicalSystemsBase = "6e36e845-645a-534a-86f2-f5d4aa5a06b4"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
DynamicalSystemsBase = "3, 2"
Reexport = "1"
StaticArrays = "1"
julia = "1.8"
